// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR1Svg7wMrAZv-hrOisQD2LzUxJPR7YfQ',
    appId: '1:467974458863:web:0c21dd91f88f757c4e3a1a',
    messagingSenderId: '467974458863',
    projectId: 'crud-e4432',
    authDomain: 'crud-e4432.firebaseapp.com',
    storageBucket: 'crud-e4432.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJBlXOAFXSO84oBVTtQPflSwPC_EtjOO0',
    appId: '1:467974458863:android:c894238f6f88ebc84e3a1a',
    messagingSenderId: '467974458863',
    projectId: 'crud-e4432',
    storageBucket: 'crud-e4432.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh5uSUstRAzSQ8vW1veLz284Kc6Mv59wk',
    appId: '1:467974458863:ios:7d041c7bfdd873584e3a1a',
    messagingSenderId: '467974458863',
    projectId: 'crud-e4432',
    storageBucket: 'crud-e4432.firebasestorage.app',
    iosBundleId: 'com.example.noteUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh5uSUstRAzSQ8vW1veLz284Kc6Mv59wk',
    appId: '1:467974458863:ios:7d041c7bfdd873584e3a1a',
    messagingSenderId: '467974458863',
    projectId: 'crud-e4432',
    storageBucket: 'crud-e4432.firebasestorage.app',
    iosBundleId: 'com.example.noteUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR1Svg7wMrAZv-hrOisQD2LzUxJPR7YfQ',
    appId: '1:467974458863:web:f550c89844c8a8404e3a1a',
    messagingSenderId: '467974458863',
    projectId: 'crud-e4432',
    authDomain: 'crud-e4432.firebaseapp.com',
    storageBucket: 'crud-e4432.firebasestorage.app',
  );
}
